# Generated by Django 5.0.4 on 2024-04-18 14:02


from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('todo', 'Category')
    Category.objects.bulk_create([
        Category(name='Work'),
        Category(name='Personal'),
        Category(name='Misc'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'), # Add dependencies if any
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]

